### ISSUE TITLE
clarification on pseudo

### ISSUE THREAD

**Issue by isspek** [iBelieveCJM/Tricks-of-Semi-supervisedDeepLeanring-Pytorch#2]
Nice repository! What is the difference between epseudo and ipseudo algortihms, and the difference between versions?
Thanks in advance.

**Comment by iBelieveCJM** [comment]
Nice question. In brief,
1. The prefixes i and e mean iteration pseudo labels and epoch pseudo labels, respectively. Iteration pseudo labels regard the class estimations in current iteration as the targets of unlabeled data. And epoch pseudo labels regard the class estimations in previous epoch as the targets of unlabeled data in current iteration.
2. The main difference between versions is how to read data for unsupervised loss. In version 1, the mini-batch data X=Concat(X_labeled, X_unlabeled). That is, the version 1 guarantees a fixed number of labeled data included in mini-batch data X. In version 2, however, the mini-batch data X = RandomSubset(dataset).
More details please refer to the codes.

**Comment by isspek** [comment]
Thank you so much for the reply.
