### ISSUE TITLE
iFixMatch VS eFixMatch

### ISSUE THREAD

**Issue by ZJUJeffLai** [iBelieveCJM/Tricks-of-Semi-supervisedDeepLeanring-Pytorch#4]
May I ask what the difference is between iFixMatch and eFixmatch? Thanks.

**Comment by iBelieveCJM** [comment]
In this repo. the prefix "i-" means training with iteration pseudo labels and "e-" means training with epoch pseudo labels. In iFixMatch, I use the prediction in current iteration as the pseudo labels. But in eFixMatch, I use the prediction in previous epoch as pseudo labels. For implementing eFixMatch, I use tensor "epoch_pslab" and "epoch_probs" to keep the prediction in previous epcoh.

**Comment by ZJUJeffLai** [comment]
Great thank you! I really like this repo! May I have your contact info? My Wechat is JeffLaiZF and my email is lzhengfeng@ucdavis.edu
