### ISSUE TITLE
etempensv1/2 got RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Float for the source

### ISSUE THREAD

**Issue by toushi68** [iBelieveCJM/Tricks-of-Semi-supervisedDeepLeanring-Pytorch#6]
Hi, 
When I run etempensv1 I got this error message:
pytorch version : 1.7.1
Files already downloaded and verified
Files already downloaded and verified
Tempens-v1 with epoch pseudo labels
------ Training epochs: 0 ------
/home/xps8500/anaconda3/envs/himp/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "main.py", line 165, in <module>
    run(config)
  File "main.py", line 160, in run
    trainer.loop(config.epochs, *loaders, scheduler=scheduler)
  File "/home/xps8500/ssdlp/trainer/eTempensv1.py", line 125, in loop
    self.train(train_data, self.print_freq)
  File "/home/xps8500/ssdlp/trainer/eTempensv1.py", line 99, in train
    return self.train_iteration(data_loader, print_freq)
  File "/home/xps8500/ssdlp/trainer/eTempensv1.py", line 56, in train_iteration
    self.epoch_pslab[idxs] = outputs.clone().detach()
RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Float for the source.

The error message from etempensv2 is:

pytorch version : 1.7.1
Files already downloaded and verified
Files already downloaded and verified
Tempens-v2 with epoch pseudo labels
------ Training epochs: 0 ------
/home/xps8500/anaconda3/envs/himp/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
/home/xps8500/anaconda3/envs/himp/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "main.py", line 165, in <module>
    run(config)
  File "main.py", line 160, in run
    trainer.loop(config.epochs, *loaders, scheduler=scheduler)
  File "/home/xps8500/ssdlp/trainer/eTempensv2.py", line 127, in loop
    self.train(label_data, unlab_data, self.print_freq)
  File "/home/xps8500/ssdlp/trainer/eTempensv2.py", line 101, in train
    return self.train_iteration(label_loader, unlab_loader, print_freq)
  File "/home/xps8500/ssdlp/trainer/eTempensv2.py", line 55, in train_iteration
    uloss  = self.mse_loss(unlab_outputs, iter_unlab_pslab)
  File "/home/xps8500/ssdlp/utils/loss.py", line 34, in mse_with_softmax
    return F.mse_loss(F.softmax(logit1,1), F.softmax(logit2,1))
  File "/home/xps8500/anaconda3/envs/himp/lib/python3.6/site-packages/torch/nn/functional.py", line 1512, in softmax
    ret = input.softmax(dim)
RuntimeError: "softmax_lastdim_kernel_impl" not implemented for 'Long'

Thanks!

**Comment by iBelieveCJM** [comment]
PyTorch 1.7 is a huge improvement over Pytroch 0.4. So, my codes can not run in pytorch 1.7. You can either use the pytorch 0.4.1 or transfer the codes from pytorch 0.4.1 to pytorch 1.7.

**Comment by toushi68** [comment]
OK, it was pretty easy. All you need is to convert 
pslab = pslab.float()
right after the creation of the initial soft_pslab n_classes.
What I got for eTempensv1 at the end:
>>>[best] lloss: 28.11046	lacc: 90.010%
and for eTempensv2:
>>>[test] lloss: 39.94209	lacc: 89.280%
